### ISSUE TITLE
Recursively enable dependencies' dependencies

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#603]
When requesting the `block2` feature in e.g. `objc2-cloud-kit`, the `block2` feature of `objc2-foundation` is not enabled, which leads to build errors, see [this](https://docs.rs/crate/objc2-cloud-kit/0.2.0/builds/1193594).

So instead of the feature flags being:
```toml
block2 = ["dep:block2"]
objc2-core-location = ["dep:objc2-core-location"]
```

They should be:
```toml
block2 = ["dep:block2", "objc2-foundation/block2", "objc2-core-location?/block2"]
objc2-core-location = ["dep:objc2-core-location"]
```
